language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
 - pip install -U pip
 - pip install -U wheel setuptools
 - pip install .[test]
# command to run tests
script: unit2
